- oidc-idp/pom.xml
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunAuthenticationSuccessHandler.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnectorRpc.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunOidcConfig.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunUserInfoRepository.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/webapp/WEB-INF/server-config.xml
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/header.tag
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- oidc-idp/src/main/webapp/WEB-INF/views/approve.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/defaultApprove.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
- pom.xml
Added custom design to the consent screen. Design can be specified by adding property into perun-mitreid.properties file. 
The property  name is "web.theme". Supported values are 
- elixir
- cesnet
- bbmri
- ceitec
If no value is provided original template is used.
Commits also implement regulation of access based on membership of user in groups allowed to access resource.
> Consent page + regulation of access

- .travis.yml
enabled Travis Continuous Integration
> enabled Travis CI

- oidc-idp/src/main/java/cz/muni/ics/oidc/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/resources/cz/muni/ics/oidc/controllers/en.properties
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
Controller has been returning only values "approve" or "unapproved", it has to return the exact result (if different than "approve") from OAuthController provided by MITREid.
> OAuthController bugfix

- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunCustomClaimDefinition.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunScopeClaimTranslationService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunUserInfoRepository.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- added ability to transform values of custom claims by replacing parts matched by a regex with a replacement string that may contain references to groups like $1 or ${g}
- the same for the "sub" claim
> implemented claim value transformation

- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunOidcConfig.java
- oidc-idp/src/main/webapp/WEB-INF/tags/copyright.tag
The footer in GUI now displays both version of MITREid and version of Perun OIDC.
> added displaying version in the GUI

- oidc-idp/src/main/java/cz/muni/ics/oidc/filters/ProxyStatisticsFilter.java
- oidc-idp/src/main/webapp/WEB-INF/data-context.xml
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
Config needs to be updated:
stats.jdbc.url
stats.jdbc.user
stats.jdbc.password
stats.tableName.identityProviders
stats.tableName.serviceProviders
> Proxy statistics are collected

- oidc-idp/src/main/resources/logback.xml
Logging now sends messages to syslog. Also the default level has been set to the debug as the syslog can filter the messages out.
> Changed logging to use SYSLOG

- oidc-idp/src/main/java/cz/muni/ics/oidc/filters/ProxyStatisticsFilter.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
* Fixed problem with getting attributeValue with UTF-8 chars from request
* Proxystatistics filter now store identifier of SP/IdP instead of only name.
* Name of the SP/IdP is stored into mapping table
> Updated Proxystatistics filter

- oidc-idp/pom.xml
- oidc-idp/src/main/java/cz/muni/ics/oidc/Mapper.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunAuthenticationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunAuthenticationUserDetailsService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnectorLdap.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnectorRpc.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunOidcConfig.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/PerunUserInfoRepository.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/filters/ProxyStatisticsFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Facility.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Group.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Member.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Model.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/PerunUser.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Resource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/RichUser.java
- oidc-idp/src/main/resources/logback.xml
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- changed PerunConnector interface to use more coarse-grained methods like isUserAllowedOnFacility()
- added method getUserGroupsAllowedOnFacility() to PerunConnector which is not used yet, but wit will be used for filtering groupNames attribute values
- implemented PerunConnectorLdap that gets data from LDAP
- PerunConnectorLdap cannot so far get all data, thus it is not used
> implemented LDAP connector

- oidc-idp/src/main/java/cz/muni/ics/oidc/elixir/DatasetPermissionsAccessTokenModifier.java
- modified DatasetPermissionsAccessTokenModifier to support permissions_rems scope
- renamed file /etc/perun/ega.properties to /etc/perun/datasets.properties
> added REMS dataset permissions

- oidc-idp/src/main/java/cz/muni/ics/oidc/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/resources/cz/muni/ics/oidc/controllers/cs.properties
- oidc-idp/src/main/resources/cz/muni/ics/oidc/controllers/en.properties
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/langbar.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/scripts.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/copyright.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
- Fixed misconfig for scopes
- Modified consent to pretty print array scopes
- Small changes in JSPs
- Translation eduPersonEntitlement
> Fixes and enhancements

- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/header.tag
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
* Renamed theme from bbmri-eric to bbmri
* Fixed loading of favicons
> Fixed mapping of web resources in BBMRI template

- oidc-idp/pom.xml
* Fixed problem that lang properties files weren't include in *.war
> Fixed build configuration

- oidc-idp/src/main/java/cz/muni/ics/oidc/filters/ProxyStatisticsFilter.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
* Updated ProxyStatisticsFilter to work with new database model
> Updated ProxyStatisticsFilter

- .travis.yml
- oidc-idp/pom.xml
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorLdap.java
Also added compatibility with Java 11.
> updated libraries to latest versions

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/PerunUserInfoService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/AddHeaderInterceptor.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/DatasetPermissionsAccessTokenModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java
- oidc-idp/src/main/resources/logback.xml
- calling EGA and REMS at Permissions API endpoints
> implemented permissions for GA4GH

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/PerunOIDCTokenService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/DatasetPermissionsAccessTokenModifier.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- implemented adding claims to ID token
- removed old Elixir Permissions API implementation
> Id token claims

- oidc-idp/src/main/resources/logback.xml
Added thread into syslog appender pattern
> Updated SYSLOG suffixPattern.

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
- oidc-idp/src/main/resources/logback.xml
Log more information about successful login for audit purposes.
> Log logins with details of service and user

- oidc-idp/src/main/java/org/mitre/openid/connect/web/EndSessionEndpoint.java
- When user clicked NO on the logout confirmation, he/she has been logged out anyway
- When user clicks NO, he/she is now redirected to the last page of service (the place logout has been called from)
> Fixed logout confirmation screen

- oidc-idp/pom.xml
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHTokenParser.java
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
modified the themeApprove.jsp page to print GA4GH JWT strings in human-readable way
> pretty printing of GA4GH claim on approve page

- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Group.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Mapper.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/PerunScopeClaimTranslationService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorLdap.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/PerunUserInfo.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/PerunUserInfoService.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/UserInfoModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/UserInfoModifierContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/UserInfoModifierInitContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/modifiers/FilterEduPersonEntitlement.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/resources/logback.xml
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- Implemented post-processing of UserInfo object
- Added filter for eduPersonEntitlement - filter out entitlements that are issued by us and not assigned to the service
> Implemented post-processing of UserInfo before releasing it to the client

- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/ControllerUtils.java
- oidc-idp/src/main/webapp/WEB-INF/tags/common/langbar.tag
-Fixed issue while generating URL for switching languages in language bar. 
-Bug caused link to contain "?null" string
> Langbar fix

- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Aup.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/Mapper.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/PerunAttribute.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/PerunAttributeDefinition.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorLdap.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthorizationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFilterConstants.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunForceAupFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/ProxyStatisticsFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/AupController.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/ControllerUtils.java
- oidc-idp/src/main/resources/localization/cs.properties
- oidc-idp/src/main/resources/localization/en.properties
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- oidc-idp/src/main/webapp/WEB-INF/views/aup.jsp
- Refactored calling of Perun filters
- Only one class represents Filter in Chain
- Other filters are called from class mentioned above
- Implemented processing of AUP (Acceptable Usage Policy)
- See changes in user-context.xml for configuration options
> Added ForceAupFilter

- oidc-idp/src/main/resources/localization/cs.properties
- oidc-idp/src/main/resources/localization/en.properties
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerBody.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerCssLinks.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerInit.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/europdx/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/europdx/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/muni/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/muni/header.tag
- oidc-idp/src/main/webapp/WEB-INF/views/registrationForm.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/registrationFormContinue.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
- Changed style of template system
- Each instance has its own header and footer
- Header in common folder is separated into several files
- Added MU template
- MU has a specific look so it does not include header files from the common folder
> Restructured templates

- oidc-idp/src/main/java/cz/muni/ics/oidc/BeanUtil.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFilterConstants.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilterParams.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunAuthorizationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunForceAupFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- refactored instantiation of filters
- allowed skipping of filters based on client_id and user principal name
- refactored fetching of filter configurations (see classes for detailed configuration)
> Request filters refactor

- configuration_templates/[lang].properties.tpl
- configuration_templates/perun-mitreid.properties.tpl
- added configuration template file with sample configuration
> Configuration template file

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunForceAupFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/AupController.java
- could not resolve placeholder for property as it has been removed
- value is sent in session attribute from filter
> Bugfix in AUP controllers

- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/bbmri/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/ceitec/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/cesnet/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerBody.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerCssLinks.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerInit.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/copyright.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/elixir/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/europdx/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/europdx/header.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/muni/footer.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/muni/header.tag
- oidc-idp/src/main/webapp/WEB-INF/views/aup.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
-Changes in themedApprove
- fixed buttons, changed positioning, changed labels for checkboxes
- changes in tags and views
- added missing directives, removed unused variables
> Changes in frontend

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java
* Fix the bug in resourceCapabilities in case the attribute is null
> Fix the bug in resourceCapabilities

- oidc-idp/src/main/java/cz/muni/ics/oidc/models/PerunAttribute.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/models/exceptions/InconvertibleValueException.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunUnapprovedRegistrationController.java
- Updated returning NULL from Perun
- If Perun returns null for list, empty list is returned
- if Perun returns null for map, empty map is returned
> Refactor valueAsXYZ() in PerunAttribute

- CHANGELOG.md
- configuration_templates/web_html_classes.properties.tpl
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/WebHtmlClasses.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/AupController.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/ControllerUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunOAuthConfirmationController.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunUnapprovedController.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunUnapprovedRegistrationController.java
- oidc-idp/src/main/resources/web_classes/web_html_classes.properties
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerInit.tag
- oidc-idp/src/main/webapp/WEB-INF/tags/muni/header.tag
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- changes in consent
- render HTML element classes from specified file
> Consent fixes

- CHANGELOG.md
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFilterConstants.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunIsCesnetEligibleFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/ControllerUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/PerunUnapprovedController.java
- oidc-idp/src/main/resources/localization/cs.properties
- oidc-idp/src/main/resources/localization/en.properties
- oidc-idp/src/main/webapp/WEB-INF/tags/common/headerInit.tag
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/unapproved_spec.jsp
- oidc-idp/src/main/webapp/resources/css/customs.css
- implemented isCesnetEligible filter
- filter checks, if given attribute has valid vlaue in specified time frame
- if user does not meet the criteria, he/she is redirected to the unapproved page
- modified unapproved page to show additional message passed from param
- moved all filter parameter names into PerunFilterconstants class
> IsCesnetEligible filter, filter params refactor

- CHANGELOG.md
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
- oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- updated to use new consolidated statistics
- refactored methods
> Refactored ProxyStatisticsFilter

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
- some removed options were still present
> Fixed javadoc for ProxyStatsFilter

- CHANGELOG.md
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/GroupNamesSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorLdap.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java
- added new claim source which simulates fetching groupNames attribute
- modified EntitlementSource to use new claim source rather than
attribute
> Added GroupNamesSource for claims, changed EntitlementSource

- CHANGELOG.md
- README.md
- oidc-idp/pom.xml
- oidc-idp/src/main/resources/logback.xml
- for logging to syslog, use -Dlog.to=SYSLOG when compiling
- for logging to rolling_file, use -Dlog.to=ROLLING_FILE when compiling
- for logging to file, use -Dlog.to=FILE when compiling
- see readme for detailed logging configuration
> Added new logging possibilities

- CHANGELOG.md
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/PerunConnector.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorLdap.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java
- added facilityCapabilities
- renamed capabilities to resourceCapailities (needed for distinction)
- optimized processing of claim
> Modified EntitlementSource

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/GroupNamesSource.java
- sort values in groupNames source
- sort values in eduperson_entitlement source
> Sorted GroupNames and Entitlements

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java
Some GA4GH Passport visas have expiration set to 1 year after some event (like last access of the user authenticated by an IdP) and thus can be already expired. This fix omits such visas.
> fixed generating expired visas

- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimModifierInitContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimSourceInitContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimSourceProduceContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/ClaimUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/PerunCustomClaimDefinition.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/modifiers/AppendModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/modifiers/GroupNamesAARCFormatModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/modifiers/RegexReplaceModifier.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EdupersonScopedAffiliationsMUSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/ExtractValuesByDomainSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/GroupNamesSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/IsCesnetEligibleClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/PerunAttributeClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/StaticValueClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/TwoArrayAttributesClaimSource.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/CallPerunFiltersFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFiltersContext.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunRequestFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/MDCFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunAuthorizationFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunForceAupFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunIsCesnetEligibleFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ProxyStatisticsFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/ValidUserFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/PerunUserInfoService.java
- server/claims/sources
- server/filters + server/filters/impl
- More logs
- More apparent logs
- Grammar fixes
- First letters capitalized (“Title case”)
- Unified structure for the whole component
- Added logs to classes without logs
- **ExtractValuesByDomainSource:** Are lines 53-55 necessary, if the check is done in the constructor?
> Logs refactoring

- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/ApproveDeviceController.java
- oidc-idp/src/main/resources/localization/cs.properties
- oidc-idp/src/main/resources/localization/en.properties
- oidc-idp/src/main/webapp/WEB-INF/views/themedDeviceApproved.jsp
- oidc-idp/src/main/webapp/WEB-INF/views/themedRequestUserCode.jsp
Done, except the broken endpoint -> page can be viewed from '/device' endpoint instead of '/devicee'.
> requestCode themed page (endpoint broken so far)

- CHANGELOG.md
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunFilterConstants.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunIsTestSpFilter.java
- oidc-idp/src/main/java/cz/muni/ics/oidc/web/controllers/IsTestSpController.java
- oidc-idp/src/main/resources/localization/cs.properties
- oidc-idp/src/main/resources/localization/en.properties
- oidc-idp/src/main/webapp/WEB-INF/views/isTestSpWarning.jsp
- not tested/not working yet
- unnecessary comments for debugging still included
> testSp warning page
