CESNET/perun-mitreid

oidc-idp/src/main/java/cz/muni/ics/oidc/PerunIntrospectionResultAssembler.java
The user claims released at Introspection Endpoint are now restricted by the intersection of 
- scopes in access token (consented by user) 
- scopes registered for the resource server making the request to Introspection Endpoint
=> restrict claims to intersection of token and resource server scopes

oidc-idp/src/main/java/cz/muni/ics/oidc/PerunCustomClaimDefinition.java, oidc-idp/src/main/java/cz/muni/ics/oidc/PerunScopeClaimTranslationService.java, oidc-idp/src/main/java/cz/muni/ics/oidc/PerunUserInfoRepository.java, oidc-idp/src/main/java/cz/muni/ics/oidc/claims/AppendModifier.java, oidc-idp/src/main/java/cz/muni/ics/oidc/claims/ClaimValueModifier.java, oidc-idp/src/main/java/cz/muni/ics/oidc/claims/ClaimValueModifierInitContext.java, oidc-idp/src/main/java/cz/muni/ics/oidc/claims/GroupNamesAARCFormatModifier.java, oidc-idp/src/main/java/cz/muni/ics/oidc/claims/RegexReplaceModifier.java, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
Custom claims and the "sub" claim now can have modifiers, which are specified in the /etc/perun/perun-mitreid.properties file using properties "attribute.openid.sub.modifierClass" or "custom.claim.&lt;claim>.modifierClass". A modifier is a class that must extend the abstract class cz.muni.ics.oidc.claims.ClaimValueModifier, and can read configuration properties during its initialization.
Three modifiers are provided: AppendModifier, RegexReplaceModifier and GroupNamesAARCFormatModifier.
The AppendModifier is intended for appending domain to the "sub" claim. The GroupNamesAARCFormatModifier is intended for converting the groupNames claim into AARC format.
=> added framework for claim value modifiers

oidc-idp/src/main/resources/logback.xml, oidc-idp/src/main/webapp/WEB-INF/tags/copyright.tag, pom.xml
Rebased on MITREid 1.3.3-SNAPSHOT to support Device code flow. Also set all logging levels to INFO, and changed the order of Perun MITREid a MITREid Connect versions reported in GUI footer.
=> rebased on MITREid 1.3.3-SNAPSHOT

oidc-idp/src/main/java/cz/muni/ics/oidc/Mapper.java, oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnector.java, oidc-idp/src/main/java/cz/muni/ics/oidc/PerunConnectorRpc.java, oidc-idp/src/main/java/cz/muni/ics/oidc/PerunUserInfoRepository.java, oidc-idp/src/main/java/cz/muni/ics/oidc/controllers/PerunOAuthConfirmationController.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/Facility.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/Group.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/Member.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/Model.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/Resource.java, oidc-idp/src/main/java/cz/muni/ics/oidc/models/RichUser.java
- Whole project updated, so connector methods return specific model objects instead of JsonNode objects.
- Many object models created, each extends abstract class Model, which has just 1 variable (id) and each class is specific with own variables due to its needs.
- One simple Mapper class created, which maps JsonNode to objects.
- Documentation updated.
=> Model objects are used as return type of methods in PerunConnector

oidc-idp/src/main/java/cz/muni/ics/oidc/filters/ProxyStatisticsFilter.java, oidc-idp/src/main/resources/logback.xml, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
The names for request attributes containing IdP's nname and id were previously hardcoded, now they are configurable.
=> added configurable names for attributes with idp name and id to statistics filter

oidc-idp/pom.xml, oidc-idp/src/main/resources/logback.xml, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
When building via maven following options can be specified:
* Added ability to specify location of the conguration file -Dconfig.location=location [default: /etc/perun/perun-mitreid.properties]
* Added ability to specify logging style -Dlog.to=FILE|SYSLOG [default: FILE]
* Added ability to specify logging contextName -Dlog.contextName=contextName [default: oidc]
* Added ability to specify logging facility (syslog) -Dlog.facility=facility [default: LOCAL7]
* Added ability to specify logging level -Dlog.level=level [default: info]
* Added ability to specify final build name -Dfinal.name=name [default: oidc]
=> Added options for running multiple instances

pom.xml
MITREid 1.3.3 was released at last, so we can use it instead of our modified version of 1.3.3-SNAPSHOT
=> rebased on MITREid 1.3.3

oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthorizationFilter.java, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- When user logs in, MitreID tries to fetch user from Perun. We can now specify name of the ext source the request should use when fetching user by his extLogin and extSourceName
- When option left empty, extSourceName is fetched from request header Shib-Identity-Provider
- When option is set, request header Shib-Identity-Provider is ignored
=> Added option to specify extSource name

oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/ElixirAccessTokenModifier.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java, oidc-idp/src/main/java/org/mitre/openid/connect/web/EndSessionEndpoint.java, oidc-idp/src/main/resources/logback.xml, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
- modified EndSessionEndpoint to redirect to SAML logout after OIDC logout and before redirect back to client
- added property proxy.logout.url that may specify non-standard logout URL
- if properties proxy.logout.url or proxy.login.url are not defined, standard shibboleth URLs are created from the OIDC issuer URL (by replacing path with /Shibboleth.sso/Logout or /Shibboleth.sso/Login)
- renamed DatasetPermissionsAccessTokenModifier to ElixirAccessTokenModifier to better match its purpose
=> implemented SAML logout

oidc-idp/src/main/webapp/WEB-INF/tags/common/header.tag
In customized themes paths to the CSS files has changed as we started using SimpleSAMLphp 1.17. This commit contains fix with new mapping.
=> Fixed path to css files

oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java
Since Perun 3.6, the lastAccess field of UserExtSource keeps the last time its atribute values were written or found to be unchanged. So it can be used for setting the "asserted" field in GA4GH claim objects holding affiliations.
=> set GA4GH affiliations expiration based on lastAccess

oidc-idp/src/main/webapp/WEB-INF/classes/db/mysql/db_update.sql, oidc-idp/src/main/webapp/WEB-INF/classes/db/psql/psql_database_tables.sql
- Changed type VARCHAR(2048) in table "authentication_holder_request_parameter" to use TEXT type.
- When using renew on testing client, MITREid tried to store the request parameter into DB. Request parameter was id_token_hint, which was too long. TEXT data type can handle it.
=> Fix in DB for SQL exception

oidc-idp/src/main/java/cz/muni/ics/oidc/server/PerunOIDCTokenService.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java, oidc-idp/src/main/webapp/WEB-INF/user-context.xml
Some non-standard claims are too large to be included into id_token, which needs to be passed in URLs. This pull request makes claims included into id_token configurable. Only claims belonging to scopes configured by id_token.scopes property are included. 
By default, only standard OIDC scopes are configured (openid,profile,email,phone,address).
=> configurable scopes for including claims into id_token

oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHTokenParser.java
JWT tokens about dataset permissions are now read from REMS, their signatures and correctness are verified, and together with a LinkedIdentities passport visa are added to the passport returned from ELIXIR AAI
=> implemented reading GA4GH JWT tokens from REMS

oidc-idp/src/main/java/cz/muni/ics/oidc/server/connectors/impl/PerunConnectorRpc.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunForceAupFilter.java
Fixed some bugs in AUP filter
- possible null pointer when entityless had no keys
- fixed logic in evaluation what AUPs need to be approved
- VO AUPs got ignored when no AUP has been requested (and it should not be ignored)
- code refactorization for better readability and understandability
=> AUP Bugfixes

oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
We added "group:" into resource capabilities while wrapping them. Now it is added just into groups.
Unfortunately, perun-mitreid.properties config file has to be changed. In eduperson_entitlement claim, "group:" has to be removed from "prefix" property.
=> Fixed bug in resource capabilities

CHANGELOG.md, oidc-idp/src/main/java/cz/muni/ics/oidc/server/configurations/PerunOidcConfig.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java
- fixed forced logout from SAML when using MFA, sometimes filter has not indicated user has been logged out and the user had to log in twice
- fixed setting of SAML logout URL when specified (bug was that login URL has been used instead)
=> Fixed bugs for Logout force, fixed wrong saml logout URL setting

CHANGELOG.md, oidc-idp/src/main/webapp/WEB-INF/views/registrationForm.jsp, oidc-idp/src/main/webapp/WEB-INF/views/registrationFormContinue.jsp
- double service name in heading has been rendered due to usage of c:if instead of c:choose tag
=> Fixed bad rendering of registration pages

CHANGELOG.md, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunAuthorizationFilter.java
- ficxed validation of custom URL provided when user does not meet criteria to access the service and should be redirected to custom registration URL
- old implementation tried to add http:// at the start of string even when https:// has been present, resulting in wrongly formated URL
- changed order of validation, first try HTTPS then HTTP
=> Fixed validating url for registrations when unapproved

oidc-idp/src/main/webapp/WEB-INF/views/themedApprove.jsp
- field had wrong ID assigned, caused checkbox to be displayed to the
left of every other field
=> Fixed display of remember me button on consent

CHANGELOG.md, configuration_templates/perun-mitreid.properties.tpl, oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/PerunUserInfoService.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/UserInfoModifierContext.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/userInfo/modifiers/FilterEduPersonEntitlement.java
- changed property names for specifying custom claims
- class of claim source specified by custom.claim.[claimName].source.class=
- properties of claim source specified by custom.claim.[claimName].source.[propName]=
- class of claim modifier specified by custom.claim.[claimName].modifier.class=
- properties of claim modifier specified by custom.claim.[claimName].modifier.[propName]=
- Fixed behavior of FilterEduPersonEntitlement User Info modifier class
- fixed possible NullPointerException when no facility could be found in Perun
- when no facility is found or no resource is found, all entitlements
matched by prefix and suffix are filtered out, meaning only resource
capabilities and forwarded entitlements are kept
- Changed way how UserInfo modifiers are loaded - now loaded only once …
=> Claim source properties, FilterEduPersonEntitlement

CHANGELOG.md, oidc-idp/src/main/java/cz/muni/ics/oidc/server/claims/sources/EntitlementSource.java
- When property eduPersonEntitlement in EntitlementSource is null or
blank, producing value will ignore the attribute with forwarded
entitlements
=> Skip forwarded entitlements if attr not specified

CHANGELOG.md, oidc-idp/pom.xml, oidc-idp/src/main/java/cz/muni/ics/oidc/server/CustomTaskScheduler.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/PerunAcrRepository.java, oidc-idp/src/main/resources/logback.xml, oidc-idp/src/main/webapp/WEB-INF/classes/db/psql/db_update.sql, oidc-idp/src/main/webapp/WEB-INF/task-config.xml
- When used in clustered environment, running scheduled task caused
DeadLocks to appear in DB
- ShedLock provides support for locking by inserting records into
special table
- !!!IMPORTANT: needs new table in DB, see SQL scripts for change!!!
=> Added ShedLock support

CHANGELOG.md, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/FiltersUtils.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/PerunAuthenticationFilter.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/PerunAuthorizationFilter.java
- In case the user has successfully logged in, later the user needed to
be found in Perun. In case the user was not found, the whole processing
dropped because of exception.
- In the case mentioned above, redirect user to the unapproved page.
=> Redirect user to unapproved if not found

CHANGELOG.md, oidc-idp/src/main/webapp/WEB-INF/classes/db/mysql/db_update.sql, oidc-idp/src/main/webapp/WEB-INF/classes/db/psql/db_update.sql
- changed column name 'ocked_at' to 'locked_at'
=> Fixed typo in Shedlock

oidc-idp/pom.xml, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHTokenParser.java
To enable any number of GA4GH Claim Repositories, the configuration of the GA4GHClaimSource was moved to a separate YAML-formatted file.
=> changed GA4GHClaimsSource config format to YAML

oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHClaimSource.java, oidc-idp/src/main/java/cz/muni/ics/oidc/server/elixir/GA4GHTokenParser.java
The java.net.URL.equals() method considers two different URLs to be equal if their hostnames resolve to the same IP address, which is obviously a broken behavior since the invention of name-based virtual web sites sharing a single IP address. Unfortunately this bug manifested itself when two URLs from CSC were added for JWKS. 
This fix used URI instead of URLs.
=> fixed bug for two different URLs to be equal in HashMap

oidc-idp/src/main/java/cz/muni/ics/oidc/server/filters/impl/MDCFilter.java
- the long session ID has been causing problems when parsing in syslog
=> Shorter session ID in the MDC log
